// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH.DAL.Data;

#nullable disable

namespace QLBH.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518202232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLBH.DAL.Entities.BienTheSanPham", b =>
                {
                    b.Property<int>("BienTheID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BienTheID"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaMau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("BienTheID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("BienTheSanPham", t =>
                        {
                            t.HasCheckConstraint("CK_BienTheSanPham_Gia", "[Gia] >= 0");

                            t.HasCheckConstraint("CK_BienTheSanPham_SoLuongTon", "[SoLuongTon] >= 0");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietID"));

                    b.Property<int>("BienTheID")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonHangID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThongTin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChiTietID");

                    b.HasIndex("BienTheID");

                    b.HasIndex("DonHangID");

                    b.ToTable("ChiTietDonHang", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietDonHang_DonGia", "[DonGia] >= 0");

                            t.HasCheckConstraint("CK_ChiTietDonHang_SoLuong", "[SoLuong] > 0");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ChiTietGioHang", b =>
                {
                    b.Property<int>("ChiTietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietID"));

                    b.Property<int>("BienTheID")
                        .HasColumnType("int");

                    b.Property<int>("GioHangID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietID");

                    b.HasIndex("BienTheID");

                    b.HasIndex("GioHangID", "BienTheID")
                        .IsUnique();

                    b.ToTable("ChiTietGioHang", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietGioHang_SoLuong", "[SoLuong] > 0");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("ChiTietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietID"));

                    b.Property<int>("BienTheID")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PhieuNhapID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ChiTietID");

                    b.HasIndex("BienTheID");

                    b.HasIndex("PhieuNhapID");

                    b.ToTable("ChiTietPhieuNhap", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietPhieuNhap_SoLuong", "[SoLuong] > 0");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.DanhMuc", b =>
                {
                    b.Property<int>("DanhMucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhMucID"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("DanhMucID");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.DonHang", b =>
                {
                    b.Property<int>("DonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonHangID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TamTinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("VoucherID")
                        .HasColumnType("int");

                    b.HasKey("DonHangID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("VoucherID");

                    b.ToTable("DonHang", t =>
                        {
                            t.HasCheckConstraint("CK_DonHang_TongTien", "[TongTien] >= 0");

                            t.HasCheckConstraint("CK_DonHang_TrangThai", "[TrangThai] IN ('ChoXuLy', 'DaThanhToan', 'DaHuy')");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.GioHang", b =>
                {
                    b.Property<int>("GioHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GioHangID"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("GioHangID");

                    b.HasIndex("KhachHangID")
                        .IsUnique();

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.KhachHang", b =>
                {
                    b.Property<int>("KhachHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangID"));

                    b.Property<string>("DiaChiMacDinh")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.HasKey("KhachHangID");

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("KhachHang", t =>
                        {
                            t.HasCheckConstraint("CK_KhachHang_GioiTinh", "[GioiTinh] IN ('Nam', 'Nu', 'Khac')");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.NhanVien", b =>
                {
                    b.Property<int>("NhanVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienID"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("NhanVienID");

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.PhieuNhap", b =>
                {
                    b.Property<int>("PhieuNhapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuNhapID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PhieuNhapID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.SanPham", b =>
                {
                    b.Property<int>("SanPhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanPhamID"));

                    b.Property<string>("ChatLieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DanhMucID")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HuongDanBaoQuan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SanPhamID");

                    b.HasIndex("DanhMucID");

                    b.ToTable("SanPham", t =>
                        {
                            t.HasCheckConstraint("CK_SanPham_GiaCoBan", "[GiaCoBan] >= 0");

                            t.HasCheckConstraint("CK_SanPham_TrangThai", "[TrangThai] IN ('HoatDong', 'Ngung', 'HetHang')");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaiKhoanID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TaiKhoan", t =>
                        {
                            t.HasCheckConstraint("CK_TaiKhoan_VaiTro", "[VaiTro] IN ('KhachHang', 'NhanVien')");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanID"));

                    b.Property<int>("DonHangID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ThanhToanID");

                    b.HasIndex("DonHangID")
                        .IsUnique();

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThanhToan", t =>
                        {
                            t.HasCheckConstraint("CK_ThanhToan_TrangThai", "[TrangThai] IN ('ChoDuyet', 'DaDuyet', 'TuChoi')");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.Voucher", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherID"));

                    b.Property<int>("DaSuDung")
                        .HasColumnType("int");

                    b.Property<decimal>("DonToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaVoucher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("VoucherID");

                    b.HasIndex("MaVoucher")
                        .IsUnique();

                    b.ToTable("Voucher", t =>
                        {
                            t.HasCheckConstraint("CK_Voucher_DaSuDung", "[DaSuDung] >= 0");

                            t.HasCheckConstraint("CK_Voucher_LoaiGiam", "[LoaiGiam] IN ('PhanTram', 'TienMat')");

                            t.HasCheckConstraint("CK_Voucher_SoLuong", "[SoLuong] >= 0");
                        });
                });

            modelBuilder.Entity("QLBH.DAL.Entities.BienTheSanPham", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.SanPham", "SanPham")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.BienTheSanPham", "BienTheSanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("BienTheID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBH.DAL.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ChiTietGioHang", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.BienTheSanPham", "BienTheSanPham")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("BienTheID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBH.DAL.Entities.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("GioHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.BienTheSanPham", "BienTheSanPham")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("BienTheID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLBH.DAL.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("PhieuNhapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.DonHang", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLBH.DAL.Entities.Voucher", "Voucher")
                        .WithMany("DonHangs")
                        .HasForeignKey("VoucherID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhachHang");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.GioHang", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.KhachHang", "KhachHang")
                        .WithMany("GioHangs")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.KhachHang", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QLBH.DAL.Entities.KhachHang", "TaiKhoanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("QLBH.DAL.Entities.NhanVien", "TaiKhoanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.PhieuNhap", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.SanPham", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.ThanhToan", b =>
                {
                    b.HasOne("QLBH.DAL.Entities.DonHang", "DonHang")
                        .WithMany("ThanhToans")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBH.DAL.Entities.NhanVien", "NhanVien")
                        .WithMany("ThanhToans")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.BienTheSanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("PhieuNhaps");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.SanPham", b =>
                {
                    b.Navigation("BienTheSanPhams");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLBH.DAL.Entities.Voucher", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
